name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 62.72.1.215 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to VPS
        run: |
          ssh root@62.72.1.215 "mkdir -p /var/www/laravel"
          scp -r * root@62.72.1.215:/var/www/laravel

      - name: Install Composer dependencies
        run: |
          ssh root@62.72.1.215 "cd /var/www/laravel && composer install --no-dev --prefer-dist --no-interaction || { echo 'Composer install failed'; exit 1; }"

      - name: SSH commands
        run: |
          ssh root@62.72.1.215 << 'EOF'
          cd /var/www/laravel
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan event:cache
          php artisan storage:link
          php artisan optimize
          EOF
